name: Generate Markmap HTML

on:
  push:
    paths:
      - content.md  # Only trigger on changes to this file
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to the latest version
        with:
          node-version: '23'  # Explicitly set Node.js version to 20 for future compatibility

      - name: Generate HTML from Markdown
        run: npx markmap-cli -o index.html content.md  # Run markmap-cli using npx

      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add index.html
          git commit -m "Auto-update Markmap HTML"
          git push -f origin main:gh-pages

