name: Generate Markmap HTML

on:
  push:
    paths:
      - content.md  # Only trigger on changes to this file
      - .github/workflows/markmap.yml  # Also trigger on changes to this file
      - pages/** 
      - _config.yml # Also trigger on changes to files in this folder
      - _layouts/** # Also trigger on changes to files in this folder
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4  # Updated to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to the latest version
        with:
          node-version: '23'  # Explicitly set Node.js version to 23 for future compatibility

      - name: Generate HTML from Markdown
        run: npx markmap-cli -o index.html content.md  # Run markmap-cli using npx

      - name: Push index.html to Target Repository
        env:
          TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          git config --global user.email "d.klewein@htl-leonding.ac.at"
          git config --global user.name "GitHub Action"
          git clone https://x-access-token:${TOKEN}@github.com/ToniBruckner/Thoughts
          cd Thoughts
          cp ../index.html .  # Copy index.html into the target repo
          cp ../_config.yml .  # Copy Jekyll config file into the target repo
          cp -r ../pages .  # Copy the entire folder into the target repo
          cp -r ../_layouts .  # Copy the entire folder into the target repo
          cp -r ../_includes .  # Copy the entire folder into the target repo
          git add index.html pages _config.yml _layouts _includes # Stage index.html and the other files
          git commit -m "Auto-update Markmap HTML and folder"
          git push origin main

