name: Generate Markmap HTML

on:
  push:
    paths:
      - content.md  # Path to your markdown file
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Markmap CLI
      run: npm install -g markmap-cli

    - name: Generate HTML from Markdown
      run: markmap-cli -o index.html mindmap.md
